// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoE39FOWR_6UjLeWo7_MqrBbnNawdQHwQ',
    appId: '1:832612410278:web:b50dd063f2c5d34b5b6567',
    messagingSenderId: '832612410278',
    projectId: 'asistenciaupeu-81d43',
    authDomain: 'asistenciaupeu-81d43.firebaseapp.com',
    storageBucket: 'asistenciaupeu-81d43.firebasestorage.app',
    measurementId: 'G-EG9M1Y1FE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp2uCWXuwbzYim9ogdM95I-qk54Tuxj_M',
    appId: '1:832612410278:android:6cf15863365d90ba5b6567',
    messagingSenderId: '832612410278',
    projectId: 'asistenciaupeu-81d43',
    storageBucket: 'asistenciaupeu-81d43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHfyo5_xtbt1vg5O5v1QPcQ_2-tSePiv8',
    appId: '1:832612410278:ios:4a58c615034ad5d55b6567',
    messagingSenderId: '832612410278',
    projectId: 'asistenciaupeu-81d43',
    storageBucket: 'asistenciaupeu-81d43.firebasestorage.app',
    iosBundleId: 'pe.edu.upeu.asistenciaUpeu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHfyo5_xtbt1vg5O5v1QPcQ_2-tSePiv8',
    appId: '1:832612410278:ios:4a58c615034ad5d55b6567',
    messagingSenderId: '832612410278',
    projectId: 'asistenciaupeu-81d43',
    storageBucket: 'asistenciaupeu-81d43.firebasestorage.app',
    iosBundleId: 'pe.edu.upeu.asistenciaUpeu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoE39FOWR_6UjLeWo7_MqrBbnNawdQHwQ',
    appId: '1:832612410278:web:bedc2c19dbc3e4015b6567',
    messagingSenderId: '832612410278',
    projectId: 'asistenciaupeu-81d43',
    authDomain: 'asistenciaupeu-81d43.firebaseapp.com',
    storageBucket: 'asistenciaupeu-81d43.firebasestorage.app',
    measurementId: 'G-6H4XMCMKGP',
  );
}
